packages:
  - 'packages/*'

catalog:
  '@clack/prompts': ^1.7.0
  '@types/node': ^24.13.2
  '@typescript-eslint/parser': latest
  cac: ^7.0.0
  eslint-plugin-import: latest
  eslint: ^9.0.0
  expect": ^30.4.1
  typescript: ^6
