name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  schedule:
    - cron: "45 21 * * 3"

env:
  INFLUENCA_MEDIA: ~/pictures-and-videos
  OTHER: false

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24]

    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10
          run_install: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Run Lint
        run: pnpm run lint

      - name: Run Build/Test
        run: pnpm test
