name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  schedule:
    - cron: "45 21 * * 3"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24]

    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10
          run_install: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run Lint
        run: pnpx eslint .

      - name: Run Build/Test
        run: pnpm test --run
