name: Preview Release
on: [push, pull_request]

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - run: npm install
      - run: npm run build

      # This publishes the temporary package to pkg.pr.new
      - name: Publish Preview
        run: npx pkg-pr-new publish
