name: Preview Release
on: [push, pull_request]

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - run: npm install
      - run: npm run build

      - name: Create fixture project
        run: |
          mkdir -p examples/stackblitz-cli/fun/pkg-pr-new-smoke
          cp -R tests/fixtures examples/stackblitz-cli/fun/pkg-pr-new-smoke

      # This publishes the temporary package to pkg.pr.new
      - name: Publish Preview
        run: npx pkg-pr-new publish --commentWithSha --bin --no-template
